#!/bin/bash
# Regenie_GWAS 0.0.01
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".
    regenie_executable=regenie_v3.0.gz_x86_64_Linux
    project=project-G6F22pjJZ8kxK7ZY291Kv225
    step1_directory=/Proteomics/step1_files/

    dx download "$Covariate_TSV" -o Covariate_TSV.gz
    dx download "$Phenotype_TSV" -o Phenotype_TSV.gz

    output_name=`dx describe "$Phenotype_TSV" --name`

    #### Make regenie executable
    chmod 777 ${regenie_executable}

    #### Make plink executable
    chmod 777 plink2
     
    #### Unzip Pheno and Covar Files
    gunzip Covariate_TSV.gz
    sed -i 's/\.b/NA/g' Covariate_TSV
    gunzip Phenotype_TSV.gz
    sed -i 's/\.b/NA/g' Phenotype_TSV

    Phenotype=$(head -n 1 Phenotype_TSV | sed 's/ /\t/g' | cut -f 3-)
    Pheno_for_plink=$(awk '{print $3;exit}' Phenotype_TSV)
    echo ${Phenotype}
    echo ${output_name} >> ${output_name}.delete
    dx mkdir -p ${project}:${step1_directory}
    dx upload ${output_name}.delete --path ${project}:${step1_directory}
    dx rm ${project}:${step1_directory}${output_name}*

    #### Download step 1 files and gunzip 
    dx download -r  ${project}:/regenie_step1_450k
    gunzip regenie_step1_450k/*

    #### Plink Filter By Phenotype 
    ./plink2 \
    --bfile regenie_step1_450k/regenie_step1_genotypes_450k_exomes_nov21 \
    --mac 100 \
    --pheno Phenotype_TSV \
    --pheno-name ${Pheno_for_plink} \
    --write-snplist \
    --1 \
    --prune \
    --out ${output_name}_snplist_mac100

    if [ $type == "Continuous" ]
    then
	    if [ "${invnorm}" == "Yes" ]; then
    	  outputdir=${output_name}_raw_sin_wgs
	    else
        outputdir=${output_name}_raw_wgs
	    fi		
    else
      outputdir=${output_name}_binary_wgs
    fi    
    regenie_com="./regenie_v3.0.gz_x86_64_Linux \
          --step 1 \
	        --bed regenie_step1_450k/regenie_step1_genotypes_450k_exomes_nov21 \
	        --phenoFile Phenotype_TSV \
	        --covarFile Covariate_TSV \
	        --bsize 1000 \
          --catCovarList $catvars \
          --maxCatLevels 30 \
	        --extract ${output_name}_snplist_mac100.snplist \
          --out ${output_name}_Step1"
    if [ $type == "Continuous" ]
    then
	    if [ "${invnorm}" == "Yes" ]; then
        regenie_com=${regenie_com}" --apply-rint"
	    fi		
    else
      regenie_com=${regenie_com}" --bt"
    fi    

    $regenie_com

    #error here
    dx upload ${output_name}* --path ${project}:${step1_directory}
    dx-jobutil-add-output output "success" --class=string
}